WHY_TOPICS = [
    "Why you can't remember being a baby (the dark truth)?",
    "Why does déjà vu happen (scientists are shocked)?",
    "Why does time move faster as you age (it's terrifying)?",
    "Why does heartbreak actually hurt your body?",
    "Why do you zone out while driving (your brain's secret)?",
    "Why does music give you chills (the hidden science)?",
    "Why do you feel like you're falling when you sleep?",
    "Why do you remember every embarrassing moment?",
    "Why do you hate your voice in recordings?",
    "Why do you get sleepy after eating (it's not food coma)?",
    "Why do you procrastinate even when you know better?",
    "Why do smells instantly transport you to childhood?",
    "Why do you crave sugar when you're sad?",
    "Why can't you stop scrolling (even when bored)?",
    "Why are Sunday scares real (psychology explained)?",
    "Why do you talk to yourself (and it's actually genius)?",
    "Why do you bite your nails without realizing?",
    "Why do you shiver when you're scared (not cold)?",
    "Why is yawning contagious (the weird truth)?",
    "Why do you sneeze when you look at the sun?",
    "Why does your heart race during horror movies?",
    "Why do you grind your teeth at night?",
    "Why do you love popping bubble wrap?",
    "Why do you feel secondhand embarrassment?",
    "Why do you crack your knuckles (the disturbing sound)?",
    "Why do you sweat when you're anxious?",
    "Why do you fidget when you're bored?",
    "Why do you pace while thinking?",
    "Why do you gasp during jump scares?",
    "Why do you root for the underdog every time?",
    "Why do you sleep better in cold rooms?",
    "Why do you love watching people fail?",
    "Why do you hate your own handwriting?",
    "Why can't you stop checking your phone?",
    "Why do you feel nostalgic for times you never lived?",
    "Why do you get hangry (it's not just hunger)?",
    "Why do you lose every sock in the laundry?",
    "Why do you scream on rollercoasters?",
    "Why do you stutter under pressure?",
    "Why do you dream more when you're sick?",
    "Why do you gain weight as you age (it's not metabolism)?",
    "Why do some people never get sick?",
    "Why do you fear the dark (even as an adult)?",
    "Why do people faint at the sight of blood?",
    "Why do you chew on pens without thinking?",
    "Why does cold weather make you hungrier?",
    "Why do humans walk on two legs (evolution's mistake?)?",
    "Why do tears taste salty (the chemical reason)?",
    "Why do you feel jet lag (your brain's time glitch)?",
    "Why do you twitch right before you fall asleep?",
    "Why do you need exactly 8 hours of sleep?",
    "Why do you like being scared on purpose?",
    "Why do toddlers ask 'why?' 300 times a day?",
    "Why do you enjoy gossip (the evolutionary advantage)?",
    "Why do kids learn languages so fast?",
    "Why do you hate certain textures (sensory secrets)?",
    "Why do you daydream 47% of your day?",
    "Why do you sleep less as you get older?",
    "Why do you feel tired after crying?",
    "Why do you look where everyone else looks?",
    "Why do you repeat things out loud to remember?",
    "Why do you crave junk food when you're depressed?",
    "Why do you love sad music when you're happy?",
    "Why do you hiccup after spicy food?",
    "Why do your eyes water when you're exhausted?",
    "Why do you like spicy food (even though it hurts)?",
    "Why do humans have fingerprints (the real reason)?",
    "Why do you snore (and how is it slowly killing you)?",
    "Why does adrenaline make you superhuman?",
    "Why do you itch for no reason?",
    "Why do you have eyebrows (evolution's gift)?",
    "Why do you love symmetrical faces?",
    "Why does caffeine actually keep you awake?",
    "Why do you get tired just from thinking hard?",
    "Why do you love horror movies (the psychology)?",
    "Why does your voice change when you're nervous?",
    "Why do you forget names 3 seconds after meeting someone?",
    "Why can't you tickle yourself?",
    "Why do you blush when embarrassed (the body's betrayal)?",
    "Why do you flinch before impact?",
    "Why do babies stare at you (it's creepy but smart)?",
    "Why do you see colors in your dreams?",
    "Why do your hands shake when you're nervous?",
    "Why do you get goosebumps from music?",
    "Why do cats purr (and why does it heal you too)?",
    "Why do you feel physical pain from rejection?",
    "Why do you laugh at dark humor?",
    "Why does your alarm sound become your enemy?",
    "Why do you lose track of time online?",
    "Why do you have a belly button (useless body part?)?",
    "Why do old people actually shrink?",
    "Why do you have pubic hair (evolution's plan)?",
    "Why do you feel pain (your body's warning system)?",
    "Why do you dream in color or black and white?",
    "Why do you talk in your sleep?",
    "Why do some people have perfect memory?",
    "Why do you feel dread on Sunday nights?",
    "Why do you get nervous before every date?",
    "Why can't you stop checking social media?",
    "Why do you sleep talk and what does it reveal?",
    "Why do you hiccup (and the weird ways to stop it)?",
    "Why do you cry when you're angry (not sad)?",
    "Why does your body temperature drop when you sleep?",
    "Why do you forget your dreams 5 minutes after waking?"
]

WHAT_IF_TOPICS = [
    "What if Earth stopped spinning for 5 seconds?",
    "What if gravity disappeared right now?",
    "What if you never had to sleep again?",
    "What if the moon vanished tonight?",
    "What if Earth had rings like Saturn?",
    "What if animals could suddenly talk tomorrow?",
    "What if dinosaurs never went extinct?",
    "What if the sun never rose again?",
    "What if you could teleport anywhere?",
    "What if everyone on Earth jumped at once?",
    "What if you used 100% of your brain?",
    "What if you could travel back in time?",
    "What if humans were immortal?",
    "What if aliens landed tomorrow?",
    "What if the internet shut down forever?",
    "What if you were the last human alive?",
    "What if you could talk to your future self?",
    "What if you could pause time?",
    "What if Earth was actually flat?",
    "What if you woke up in a parallel universe?",
    "What if money didn't exist?",
    "What if Earth ran out of water tomorrow?",
    "What if you were completely transparent?",
    "What if you lived the same day forever?",
    "What if animals ruled the world?",
    "What if your dreams predicted the future?",
    "What if everyone could read minds?",
    "What if you switched bodies for a day?",
    "What if oxygen disappeared for 10 seconds?",
    "What if Earth was completely hollow?",
    "What if you couldn't feel any pain?",
    "What if babies were born with adult intelligence?",
    "What if sharks could fly?",
    "What if humans lived underwater?",
    "What if robots took over tomorrow?",
    "What if you physically couldn't lie?",
    "What if your reflection started moving differently?",
    "What if humans had 3 arms?",
    "What if you could see the 4th dimension?",
    "What if gravity worked in reverse?",
    "What if you could turn invisible at will?",
    "What if your life was just a simulation?",
    "What if humans had tails like animals?",
    "What if the sky turned green forever?",
    "What if every lie was instantly exposed?",
    "What if you could eat without ever gaining weight?",
    "What if sound traveled at light speed?",
    "What if your phone could read your thoughts?",
    "What if you never needed to breathe?",
    "What if you could download knowledge instantly?",
    "What if all insects disappeared tomorrow?",
    "What if you were born 500 years ago?",
    "What if gravity only worked at the poles?",
    "What if humans were naturally nocturnal?",
    "What if dreams could be recorded and watched?",
    "What if language never existed?",
    "What if Earth was twice its current size?",
    "What if your thoughts appeared as holograms?",
    "What if you could smell colors?",
    "What if fish could breathe air?",
    "What if your pet could talk for one day?",
    "What if gravity was 10 times stronger?",
    "What if humans had built-in WiFi?",
    "What if Earth spun twice as fast?",
    "What if humans only lived to age 30?",
    "What if time only moved at night?",
    "What if humans laid eggs instead of giving birth?",
    "What if you could control the weather?",
    "What if mirrors didn't exist?",
    "What if humans had fur like animals?",
    "What if water became poisonous to humans?",
    "What if computers could dream?",
    "What if history repeated every 100 years?",
    "What if humans had wings instead of arms?",
    "What if Earth was inside a black hole?",
    "What if your brain had WiFi access?",
    "What if you could press 'undo' on real life?",
    "What if your brain had a storage limit?",
    "What if every dream was actually real?",
    "What if sleep became illegal worldwide?",
    "What if you met your alternate universe self?",
    "What if colors didn't exist?",
    "What if humans could photosynthesize like plants?",
    "What if you could feel other people's pain?",
    "What if memory could be transferred between people?",
    "What if you aged in reverse?",
    "What if Earth had no seasons?",
    "What if humans could hibernate like bears?",
    "What if you could change your DNA at will?",
    "What if death was optional?",
    "What if you could experience all 5 senses as colors?",
    "What if humans could regenerate like lizards?",
    "What if you could split into multiple versions of yourself?",
    "What if emotions were visible as auras?",
    "What if you could absorb knowledge by touch?",
    "What if humans could communicate through telepathy?",
    "What if you could save and load your life like a game?",
    "What if every human had a superpower?",
    "What if you could trade years of your life for money?",
    "What if aging could be turned on and off?",
    "What if you could experience time in slow motion?",
    "What if humans could phase through solid objects?",
    "What if you could copy and paste physical objects?",
    "What if everyone's lifespan was visible above their head?",
    "What if you could rewind conversations?",
    "What if humans had magnetic powers?",
    "What if you could feel what you see in movies?"
]

HIDDEN_TRUTHS_TOPICS = [
    "How billionaires pay $0 in taxes (100% legal)",
    "Why casinos are designed to destroy your brain",
    "How social media is literally rewiring your mind",
    "Why influencers fake their entire lives (exposed)",
    "How McDonald's hacks your brain chemistry",
    "Why productivity culture is a massive scam",
    "Why schools haven't changed since 1800 (on purpose)",
    "How loyalty programs turn you into a gambling addict",
    "Why smart people fall for obvious scams",
    "Why we trust confident idiots over quiet experts",
    "How colors manipulate you into spending money",
    "Why 95% of people never build real wealth",
    "Why tipping culture is modern day slavery",
    "How brands make you feel poor (then sell solutions)",
    "Why minimalism is just rich people flexing",
    "Why everything became a subscription (the dark plan)",
    "How your phone listens to everything you say",
    "Why luxury brands never go on sale",
    "How Netflix designed the perfect addiction machine",
    "Why your brain can't tell fake news from real news",
    "How TikTok is destroying your attention span",
    "Why 'lucky' people create their own luck",
    "How MLMs use cult psychology to trap you",
    "Why lottery tickets are the poor person's tax",
    "How ads hack your subconscious mind",
    "Why hustle culture is toxic capitalism disguised as self-help",
    "How authority figures control you without you knowing",
    "Why billionaires buy art they never look at",
    "How social media makes you hate your life",
    "Why outrage is the internet's most valuable currency",
    "How your smartphone changes your brain structure",
    "Why most diets are designed to fail (on purpose)",
    "How attention became more valuable than gold",
    "Why beauty standards change every decade (it's not natural)",
    "How childhood ads control your adult purchases",
    "Why self-help is a $13 billion industry that doesn't work",
    "How debt slavery keeps 80% of people poor",
    "Why dopamine is making you miserable",
    "How video games use gambling psychology on kids",
    "Why clickbait works even when you know it's clickbait",
    "How the rich avoid 9-to-5 jobs (the system they don't teach)",
    "Why school kills creativity (by design)",
    "How your job is designed to feel meaningless",
    "Why social credit systems are already here",
    "How FOMO was engineered to control you",
    "Why influencers cry on camera (the psychology)",
    "How quitting your job can make you rich",
    "Why 'fake it till you make it' actually works",
    "How nostalgia is used to empty your wallet",
    "Why rich kids always stay rich (the hidden system)",
    "How conspiracy theories spread like viruses",
    "Why billionaires never use cash (the secret reason)",
    "How YouTubers hack your brain for views",
    "Why outrage content dominates your feed",
    "How fear-based headlines control your worldview",
    "Why you're addicted to drama (even if you hate it)",
    "How CEOs legally manipulate stock prices",
    "Why everything is becoming a monthly payment",
    "How brands hijack your personal identity",
    "Why you copy rich people without realizing it",
    "How microtransactions generate billions from kids",
    "Why simple apps make more money than complex ones",
    "How AI is trained on your private content",
    "Why expensive = better in your subconscious",
    "How silence is used as a psychological weapon",
    "Why people fake success on social media",
    "How the algorithm knows you better than your family",
    "Why companies create problems they later solve",
    "How personality tests reveal your deepest insecurities",
    "Why we romanticize struggle (it benefits the rich)",
    "How pricing psychology makes you spend 40% more",
    "Why human attention is the new oil",
    "How dating apps keep you single (on purpose)",
    "Why free apps cost more than paid ones",
    "How streaming services use psychology to hook you",
    "Why credit scores are modern day slavery",
    "How fast fashion exploits your insecurities",
    "Why subscription models are financial traps",
    "How social proof manipulates your decisions",
    "Why influencer marketing is more powerful than TV ads",
    "How gamification turns everything into addiction",
    "Why rich people never retire (the real reason)",
    "How insurance companies legally steal your money",
    "Why banks want you to stay in debt forever",
    "How Big Pharma creates lifelong patients",
    "Why college is the biggest scam in America",
    "How real estate keeps the middle class poor",
    "Why taxes are designed to confuse you",
    "How credit cards are designed to destroy you",
    "Why financial literacy isn't taught in schools",
    "How corporations buy politicians (100% legal)",
    "Why healthcare costs keep rising (it's not what you think)",
    "How food companies engineered addiction",
    "Why diet culture never wants you to succeed",
    "How the news media profits from your fear",
    "Why social media influencers are modern day cult leaders",
    "How your data is worth more than your salary",
    "Why poverty is profitable for corporations",
    "How planned obsolescence wastes your money",
    "Why the American dream is actually a nightmare",
    "How capitalism turned self-care into consumerism",
    "Why mental health apps make you more anxious",
    "How the gig economy eliminated job security",
    "Why mindfulness became a billion dollar industry",
    "How wellness culture preys on insecurity",
    "Why crypto was never about financial freedom",
    "How NFTs were the perfect Ponzi scheme",
    "Why social media activism never changes anything"
]